"""
Pydantic models for the related-notes agent endpoint.

RelatedNotesResponse caps related at 3 — same limit enforced in note_agent.
reason is the LLM's explanation; required for research UX transparency.
"""

from typing import Literal

from pydantic import BaseModel, Field

MAX_BOOK_LENGTH = 30
MAX_NOTE_LENGTH = 150
MAX_REASON_LENGTH = 200
MAX_PROMPT_INPUT_LENGTH = 1000
MAX_ARTICLE_TEXT_LENGTH = 12000
MAX_ARTICLE_SUMMARY_LENGTH = 500
MAX_PATHWAY_TITLE_LENGTH = 120
MAX_PATHWAY_WHY_LENGTH = 280
MAX_PATHWAY_FIRST_STEP_LENGTH = 220


class ResearchPathwaysRequest(BaseModel):
    """Input payload for generating research pathways from article text."""
    article_text: str = Field(min_length=50, max_length=MAX_ARTICLE_TEXT_LENGTH)
    focus_area: Literal["bio", "security", "ai", "software", "general"] = "general"
    pathways_count: int = Field(default=5, ge=3, le=8)


class ResearchPathwayItem(BaseModel):
    """One actionable research direction generated by the agent."""
    title: str = Field(min_length=5, max_length=MAX_PATHWAY_TITLE_LENGTH)
    why_it_matters: str = Field(min_length=20, max_length=MAX_PATHWAY_WHY_LENGTH)
    difficulty: Literal["easy", "medium", "hard"]
    first_step: str = Field(min_length=10, max_length=MAX_PATHWAY_FIRST_STEP_LENGTH)
    search_queries: list[str] = Field(min_length=1, max_length=3)


class ResearchPathwaysResponse(BaseModel):
    """Agent response: short article summary + ranked research pathways."""
    article_summary: str = Field(min_length=30, max_length=MAX_ARTICLE_SUMMARY_LENGTH)
    pathways: list[ResearchPathwayItem] = Field(min_length=3, max_length=8)


class RelatedNoteItem(BaseModel):
    """One note selected as related to a source note."""
    note_id: int = Field(gt=0)
    book: str = Field(min_length=1, max_length=MAX_BOOK_LENGTH)
    chapter: int = Field(gt=0)
    note: str = Field(min_length=1, max_length=MAX_NOTE_LENGTH)
    reason: str = Field(min_length=1, max_length=MAX_REASON_LENGTH)


class RelatedNotesResponse(BaseModel):
    """Response payload for POST /notes/{id}/related."""
    source_note_id: int = Field(gt=0)
    related: list[RelatedNoteItem] = Field(max_length=3)


class CreateNoteFromPromptRequest(BaseModel):
    """Free-form input sent for extraction into note fields."""
    prompt_input: str = Field(min_length=1, max_length=MAX_PROMPT_INPUT_LENGTH)


class CreateNoteFromPromptResponse(BaseModel):
    """Extracted note draft returned to the user before saving."""
    book: str = Field(min_length=1, max_length=MAX_BOOK_LENGTH)
    chapter: int = Field(gt=0)
    note: str = Field(min_length=1, max_length=MAX_NOTE_LENGTH)
    ai_message: str = Field(min_length=1, max_length=MAX_REASON_LENGTH)

